name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ci:
    name: Teste (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Ruodar testes
        run: npm test
        working-directory: app

  cd:
    name: Deploy (CD)
    needs: ci
    runs-on: ubuntu-latest

    evironment:
      name: staging

      steps:
        - name: Checkout do código
          uses: actions/checkout@v3

        - name: Simular deploy
          run: echo "Deploy realizado com sucesso!"