name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Rodar testes
        run: node test.js
        working-directory: app

  cd:
    needs: ci
    runs-on: ubuntu-latest

    environment:
      name: staging

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy para staging
        run: echo "Deploying realizado com sucesso!"
      